default_platform(:ios)

platform :ios do
  desc "Build and upload a beta build to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: "8ADBXLN97S",
      issuer_id: "89f06065-abc3-4944-b620-bbf05d7f174b",
      key_filepath: "fastlane/real_ser.p8"
    )

    increment_build_number(xcodeproj: "Runner.xcodeproj")
    get_provisioning_profile(
      api_key: api_key,
      app_identifier: "com.clever.lifestyle",
      team_id: "W3N4W6AVQA",
      provisioning_name: "Clever Lifestyle AppStore",
      filename: "Clever_Lifestyle_AppStore.mobileprovision",
      output_path: "fastlane/profiles",
      readonly: false
    )
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store"
    )
    upload_to_testflight(api_key: api_key)
  end
end
